### ISSUE TITLE
Remove testing suite before submitting assignment

### ISSUE THREAD

**Issue by TomasBorsje** [TomasBorsje/SWEN225-Assignment1#11]
The Assignment handout states that the code should only use the base java library, therefore we should probably get rid of JUnit and the testing suite before submitting the assignment to make sure it runs on the marking systems.

**Comment by Lucas-ws** [comment]
> The Assignment handout states that the code should only use the base java library, therefore we should probably get rid of JUnit and the testing suite before submitting the assignment to make sure it runs on the marking systems.

Obviously we don't submit the tests. You don't package the tests with your final release!

**Comment by TomasBorsje** [comment]
nevermind, you are correct. I assumed IntelliJ automatically bundled tests with the release but it seems there is a checkbox to not include them. closing!!

**Comment by Lucas-ws** [comment]
> nevermind, you are correct. I assumed IntelliJ automatically bundled tests with the release but it seems there is a checkbox to not include them. closing!!

Keep in mind that even if you submit tests it wouldn't be an issue. Tests aren't run by anything other than a test runner so the submission system wouldn't touch them.

**Comment by TomasBorsje** [comment]
forgot the tests weren't under the src package, where the compiler would attempt to import JUnit and fail.
